version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: patientdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: DockerFile  # Specify the exact filename
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # match your .env settings
      DATABASE_URL: postgres://postgres:password123@db:5432/patientdb?sslmode=disable
      JWT_SECRET: supersecretkey
    restart: on-failure

volumes:
  db_data:
